import time
from appium.webdriver.common.appiumby import AppiumBy
from scroll_and_find import Scroll_and_Find


class Share_data:
    def __init__(self, driver):
        self.driver = driver
        self.scroll_and_find = Scroll_and_Find(self.driver)

    def share_data(self):
        time.sleep(3)
        element = AppiumBy.XPATH, '//android.widget.TextView[@resource-id="vitalgain.jp:id/dashboard_micro_title_tv" and @text="Data sharing"]'
        self.scroll_and_find.scroll_and_find(element)
        time.sleep(5)
        find = self.driver.find_element(AppiumBy.XPATH, '(//android.widget.Button[@text="glossary"])[1]')
        find.click()
        time.sleep(3)
        find_box = self.driver.find_element(AppiumBy.XPATH, '//android.widget.EditText')
        find_box.send_keys('tram')
        time.sleep(3)
        # select_user = self.driver.find_element(AppiumBy.XPATH,
        #                                        '//android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View/android.widget.TextView[2]')
        # select_user.click()
        self.driver.tap([(665, 400)])
        time.sleep(3)
        cb_step = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Step"]')
        cb_step.click()
        cb_sleep = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Sleep"]')
        cb_sleep.click()
        cb_heart = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Heart rate"]')
        cb_heart.click()
        cb_resting = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Resting heart rate"]')
        cb_resting.click()
        cb_stress = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Stress"]')
        cb_stress.click()
        cb_dwt = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Desk work time"]')
        cb_dwt.click()
        cb_kcal = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Kcal out"]')
        cb_kcal.click()
        cb_pressure = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Blood pressure"]')
        cb_pressure.click()
        cb_glucose = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Blood glucose"]')
        cb_glucose.click()
        cb_body = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Body Composition"]')
        cb_body.click()
        time.sleep(3)
        ok_btn = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="OK"]')
        ok_btn.click()
        agreement = self.driver.find_element(AppiumBy.XPATH,
                                             '//android.widget.TextView[@text="Agreement provided by a third party"]')
        agreement.click()
        back = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="close"]')
        back.click()
        ok_1_btn = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="OK"]')
        ok_1_btn.click()
        time.sleep(2)
        cb_agree = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox')
        cb_agree.click()
        ok_1_btn.click()
        back_2 = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="menu"]')
        back_2.click()
        inviter = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="Inviter"]')
        inviter.click()
        time.sleep(2)
        view_user = self.driver.find_element(AppiumBy.XPATH,
                                             '//android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View/android.view.View[1]/android.view.View[2]')
        view_user.click()
        time.sleep(2)
        weeks = self.driver.find_element(AppiumBy.XPATH, '//android.view.View[@text="Weeks"]')
        weeks.click()
        time.sleep(3)
        months = self.driver.find_element(AppiumBy.XPATH, '//android.view.View[@text="Months"]')
        months.click()
        back_3 = self.driver.find_element(AppiumBy.XPATH, '(//android.widget.Button[@text="menu"])[1]')
        back_3.click()
        time.sleep(3)
        invitee = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="Invitee"]')
        invitee.click()
        time.sleep(3)
        # dot = self.driver.find_element(AppiumBy.XPATH, '//android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View[1]/android.view.View[1]/android.widget.Button[1]')
        # dot.click()
        self.driver.tap([(650, 400)])
        time.sleep(2)
        setting = self.driver.find_element(AppiumBy.XPATH, '//android.view.MenuItem[@text="Data setting"]')
        setting.click()
        time.sleep(2)
        cb_body_2 = self.driver.find_element(AppiumBy.XPATH, '//android.widget.CheckBox[@text="Body Composition"]')
        cb_body_2.click()
        update = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="UPDATE"]')
        update.click()
        time.sleep(2)
        self.driver.tap([(650, 400)])
        delete = self.driver.find_element(AppiumBy.XPATH, '//android.view.MenuItem[@text="Delete"]')
        delete.click()
        time.sleep(3)
        yes_btn = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="YES"]')
        yes_btn.click()
        # delete = self.driver.find_element(AppiumBy.XPATH, '//android.view.ViewGroup/android.webkit.WebView/android.webkit.WebView/android.view.View/android.view.View[1]/android.view.View[1]/android.widget.Image[1]')
        # delete.click()
        # time.sleep(3)
        # self.driver.tap([(660, 400)])
        # time.sleep(3)
        # yes_btn = self.driver.find_element(AppiumBy.XPATH, '//android.widget.Button[@text="YES"]')
        # yes_btn.click()

        time.sleep(3)
        light = self.driver.find_element(AppiumBy.XPATH, '(//android.widget.Button[@text="glossary"])[2]')
        light.click()
        time.sleep(5)
        back_4 = self.driver.find_element(AppiumBy.XPATH, '//android.widget.ImageButton[@content-desc="Navigate up"]')
        back_4.click()
        print("Data sharing - Done! ")
